name: Cargo Build & Test

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to crates.io

    runs-on: ubuntu-latest
    environment: crates.io

    steps:
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2

      - name: Publish
        # https://doc.rust-lang.org/cargo/reference/config.html?highlight=CARGO_REGISTRY_TOKEN#credentials
        run: >
          cargo workspaces publish
          --verbose
          --allow-branch *
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
